# Site settings
title: Adam Mazel
author:
  name: Adam Mazel
  email: mazeladam@gmail.com
description: "Professional Website: About, Résumé, Projects"

# Build settings
# theme: jekyll-theme-merlot
# minima:
  # skin: solarized-dark
